# Generated by Django 3.0 on 2021-05-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField()),
                ('serial_no', models.IntegerField()),
                ('barcode', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('location_id', models.CharField(max_length=20)),
                ('unit_id', models.CharField(max_length=20)),
                ('date_receive', models.DateTimeField()),
                ('qty', models.IntegerField(default=0)),
            ],
        ),
    ]
